
services:

  # Web Server Service
  order_nginx:
    image: nginx:alpine
    container_name: order_nginx
    # ports:
    #   - "8081:81"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - order_app
      - order_db
    networks:
      - shopping

  #Database Service
  # order_db:
  #   image: postgres:15
  #   container_name: order_db
  #   ports:
  #     - "5433:5432"
  #   environment: 
  #     POSTGRES_DB: Order
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password 
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data
  #   networks:
  #     - shopping

  # Application Service
  order_app:
    container_name: order_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    #user: "${UID}:${GID}"
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9001:9000"
    # working_dir: /var/www
    # command: sh /var/www/entrypoint.sh
    restart: always
    networks:
      - shopping

  # order_queue:
  #   build: 
  #     context: ./php
  #   container_name: order_queue
  #   volumes:
  #     - ./src:/var/www
  #   working_dir: /var/www
  #   command: php artisan queue:work rabbitmq --sleep=1 --tries=3 --timeout=60
  #   restart: always
  #   networks:
  #     - shopping

networks:
  shopping:
    external: true
    